# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#intro"
  weight = 10

[[main]]
  name = "News"
  url = "#news"
  weight = 15

[[main]]
  name = "People"
  url = "#people"
  weight = 20

[[main]]
  name = "Researches"
  url = "researches/"
  weight = 30

[[main]]
  name = "Software"
  url = "software/"
  weight = 40

[[main]]
  name = "Publications"
#  url = "#featured"
  url = "publication/"
  weight = 50

[[main]]
  name = "Teaching"
  url = "courses/"
  weight = 60

[[main]]
  name = "Groupmeeting"
  url = "https://migg-ntu.github.io/MIG_Docs/group-meeting/"
  weight = 70

[[main]]
  name = "Docs"
  url = "https://migg-ntu.github.io/MIG_Docs/"
  weight = 80

[[main]]
  name = "Positions"
#  url = "#positions"
  url = "./positions"
  weight = 90

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 100

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
